/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee;

import jaco.mp3.player.MP3Player;
import java.io.File;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleConnection;
import oracle.jdbc.OracleDriver;
import oracle.jdbc.OracleResultSet;
import oracle.jdbc.OracleStatement;

/**
 *
 * @author dell
 */
@SuppressWarnings("serial")
public class JobList extends javax.swing.JFrame {
    
    public JobList() {
        initComponents();
    }
     Thread t = new Thread (new Runnable() {
            @Override
            public void run() {
                    for(int i = 0; i<=100;i++)
                    {
                            
                        try {
                            jProgressBar1.setValue(i);
                            Thread.sleep(5);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(JobList.class.getName()).log(Level.SEVERE, null, ex);
                        }
                            
                            
                     }
            }
                    
            
        });
     public static final String Son ="D:\\error-1-126514.mp3";
    public static final String SONG ="D:\\interface-124464.mp3";
    
    MP3Player mp = new MP3Player(new File(Son));
    MP3Player mp3player = new MP3Player(new File(SONG));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("JOB LISTS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(870, 70, 220, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("JOB TYPE:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 230, 200, 60);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Developer(full-stack)", "Database administrator", "Designer", "DevOps specialist", "Software Engineer", "Educator", "Data Scientist", "Senior executive", "Marketing professional", "Product Manager", "IT architect" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(500, 230, 220, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("P_PIN:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 310, 120, 50);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(500, 320, 280, 30);

        jButton1.setText("APPLY");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 400, 110, 40);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(-10, 780, 1550, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/1393189.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-290, -240, 2120, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    @SuppressWarnings("deprecation")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try
        {
            DriverManager.registerDriver(new OracleDriver());
            OracleConnection oconn = (OracleConnection)DriverManager.getConnection("dbc:oracle:thin:@DESKTOP-COTHCMM:1522:orcl","SOUMYAJIT","CHATTOPADHYAY"); 
            OracleStatement ostmt = (OracleStatement)oconn.createStatement();
            String job,pin;
            job=jComboBox1.getSelectedItem().toString();
            pin=jTextField1.getText();
            OraclePreparedStatement pstmt =(OraclePreparedStatement)oconn.prepareStatement("SELECT COUNT(*) FROM job_profile WHERE p_pin=?");
            pstmt.setString(1,pin);
            OracleResultSet ors = (OracleResultSet)pstmt.executeQuery(); 
                    if(ors.next())
                        if(ors.getString(1).equals("1"))
                        {
                            t.start();
                            String sql = "insert into JOB_LIST values('"+job+"','"+pin+"')";
                            ostmt.executeUpdate(sql);
                            OraclePreparedStatement pstt =(OraclePreparedStatement)oconn.prepareStatement("SELECT * FROM registration");
                            OracleResultSet or = (OracleResultSet)pstt.executeQuery();
                            String a="",b="",c="",d="",e="",f="",g="";
                            while (or.next())
                            {
                            a= String.valueOf(or.getString("email"));
                            b= String.valueOf(or.getString("first_name"));
                            c= String.valueOf(or.getString("last_name"));
                            d= String.valueOf(or.getString("location"));
                            e= String.valueOf(or.getString("skills"));
                            f= String.valueOf(or.getString("gender"));
                            g= String.valueOf(or.getString("industry"));
                            }
                            sql ="insert into profile values('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"','"+f+"','"+g+"','"+job+"')";
                            ostmt.executeUpdate(sql);
                            sql = "delete registration";
                            ostmt.executeUpdate(sql);
                            sql = "commit";
                            ostmt.executeUpdate(sql);
                            mp3player.play();
                            JOptionPane.showMessageDialog(this,"Successfully Applied!");
                            JOptionPane.showMessageDialog(this,"Going back to home page...");
                            Homepage ob = new Homepage();
                            ob.show();
                        }
                    
                    else {
                            mp.play();
                        JOptionPane.showMessageDialog(this,"P_Pin not found!");
            }
        }        
            
        
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
